### ISSUE TITLE
Replace Nashorn

### ISSUE THREAD

**Issue by adrienbaron** [VueGWT/vue-gwt#68]
Nashorn engine has been deprecated as from JDK11, and is removed in JDK12.
We should find a solution to replace it.
Either using GraalVM: https://github.com/graalvm/graal-js-jdk11-maven-demo
Or Rhino: https://github.com/mozilla/rhino

**Comment by mdavis95** [comment]
I would vote GraalVM

**Comment by mdavis95** [comment]
Where is the class that calls nashorn currently?

**Comment by adrienbaron** [comment]
@mdavis95 
https://github.com/VueGWT/vue-gwt/blob/master/processors/src/main/java/com/axellience/vuegwt/processors/component/template/builder/compiler/NashornVueTemplateCompiler.java

**Comment by adrienbaron** [comment]
Ok! Looks easy enough then! Even better they seem to support Node, so we might even not have to run webpack to bundle all the JS of the template compiler together and commit the result, and just import the npm dependency 👌

**Comment by mdavis95** [comment]
Awesome.  This is a nice demo because it shows the dependencies to run graal js without the graalvm itself (https://github.com/graalvm/graal-js-jdk11-maven-demo/blob/master/pom.xml) and how to run graal as a scriptengine replacement and as the new graal polyglot context (https://github.com/graalvm/graal-js-jdk11-maven-demo/blob/master/src/main/java/com/mycompany/app/App.java#L120)

**Comment by adrienbaron** [comment]
Done as part of `Beta-10-SNAPSHOT`: https://github.com/VueGWT/vue-gwt/commit/ceb3ccacbacf36a74ec2d5c6a127c3543019fa58
